#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    create type transaction_type as enum ('incoming', 'outgoing');

    alter type transaction_type owner to postgres;

    create table if not exists "user"
    (
      id bigint generated by default as identity
        constraint user_pkey
          primary key,
      name varchar(200) not null,
      email varchar(150) not null,
      password varchar(500) not null
    );

    alter table "user" owner to postgres;

    create table if not exists agent
    (
      id bigint generated by default as identity
        constraint agent_pkey
          primary key,
      name varchar(150) not null
        constraint agent_uniq_name
          unique,
      user_id bigint
        constraint fk_agent_user
          references "user"
    );

    alter table agent owner to postgres;

    create table if not exists category
    (
      id bigint generated by default as identity
        constraint category_pkey
          primary key,
      name varchar(150) not null
        constraint category_name_uniq
          unique
    );

    alter table category owner to postgres;

    create table if not exists transaction
    (
      id bigint generated by default as identity
        constraint transaction_pkey
          primary key,
      source_agent_id bigint not null
        constraint transaction_agent_id_fk
          references agent,
      destination_agent_id bigint not null
        constraint transaction_agent_id_fk_2
          references agent,
      count money not null,
      date date default now(),
      category_id bigint not null
        constraint transaction_category_id_fk
          references category,
      transaction_type transaction_type not null
    );

    alter table transaction owner to postgres;
EOSQL